
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql+psycopg://varun:123@db:5432/ai_project
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  front-end:
    build:
      context: ./front-end
    container_name: front-end
    ports:
      - "3000:3000"
    env_file:
      - ./front-end/.env  
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ai_project
      POSTGRES_USER: varun
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U varun -d ai_project"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  postgres_data:
